# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WidgetConfigurarDrum.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetConfigurarDrum(object):
    def setupUi(self, WidgetConfigurarDrum):
        WidgetConfigurarDrum.setObjectName("WidgetConfigurarDrum")
        WidgetConfigurarDrum.resize(1280, 1035)
        self.gridLayout = QtWidgets.QGridLayout(WidgetConfigurarDrum)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 7, 1, 1)
        self.saveConfigurationButton = QtWidgets.QPushButton(WidgetConfigurarDrum)
        self.saveConfigurationButton.setObjectName("saveConfigurationButton")
        self.gridLayout.addWidget(self.saveConfigurationButton, 0, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(WidgetConfigurarDrum)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 0, 1, 1, 1)
        self.portsConnectedButton = QtWidgets.QPushButton(WidgetConfigurarDrum)
        self.portsConnectedButton.setObjectName("portsConnectedButton")
        self.gridLayout.addWidget(self.portsConnectedButton, 1, 1, 1, 1)
        self.portsConnectedTextEdit = QtWidgets.QPlainTextEdit(WidgetConfigurarDrum)
        self.portsConnectedTextEdit.setTabChangesFocus(False)
        self.portsConnectedTextEdit.setReadOnly(True)
        self.portsConnectedTextEdit.setObjectName("portsConnectedTextEdit")
        self.gridLayout.addWidget(self.portsConnectedTextEdit, 1, 2, 1, 1)
        self.midiPort_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.midiPort_Label.setAutoFillBackground(True)
        self.midiPort_Label.setObjectName("midiPort_Label")
        self.gridLayout.addWidget(self.midiPort_Label, 2, 1, 1, 1)
        self.portMidiSpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.portMidiSpinBox.setObjectName("portMidiSpinBox")
        self.gridLayout.addWidget(self.portMidiSpinBox, 2, 2, 1, 1)
        self.midi1_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.midi1_Label.setAutoFillBackground(True)
        self.midi1_Label.setObjectName("midi1_Label")
        self.gridLayout.addWidget(self.midi1_Label, 3, 4, 1, 1)
        self.midi2_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.midi2_Label.setAutoFillBackground(True)
        self.midi2_Label.setObjectName("midi2_Label")
        self.gridLayout.addWidget(self.midi2_Label, 3, 5, 1, 1)
        self.key_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.key_Label.setAutoFillBackground(True)
        self.key_Label.setObjectName("key_Label")
        self.gridLayout.addWidget(self.key_Label, 3, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.lane1A_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane1A_Label.setAutoFillBackground(True)
        self.lane1A_Label.setObjectName("lane1A_Label")
        self.gridLayout.addWidget(self.lane1A_Label, 4, 1, 1, 1)
        self.midi2_lane1A_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane1A_SpinBox.setMaximum(2000)
        self.midi2_lane1A_SpinBox.setObjectName("midi2_lane1A_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane1A_SpinBox, 4, 5, 1, 1)
        self.auto_lane1A_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane1A_CheckBox.setChecked(True)
        self.auto_lane1A_CheckBox.setObjectName("auto_lane1A_CheckBox")
        self.gridLayout.addWidget(self.auto_lane1A_CheckBox, 4, 2, 1, 1)
        self.midi1_lane1A_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane1A_SpinBox.setMaximum(2000)
        self.midi1_lane1A_SpinBox.setObjectName("midi1_lane1A_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane1A_SpinBox, 4, 4, 1, 1)
        self.key_lane_1A_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_1A_LineEdit.setObjectName("key_lane_1A_LineEdit")
        self.gridLayout.addWidget(self.key_lane_1A_LineEdit, 4, 6, 1, 1)
        self.key_lane_1B_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_1B_LineEdit.setObjectName("key_lane_1B_LineEdit")
        self.gridLayout.addWidget(self.key_lane_1B_LineEdit, 8, 6, 1, 1)
        self.midi1_lane11_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane11_SpinBox.setMaximum(2000)
        self.midi1_lane11_SpinBox.setObjectName("midi1_lane11_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane11_SpinBox, 5, 4, 1, 1)
        self.lane11_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane11_Label.setAutoFillBackground(True)
        self.lane11_Label.setObjectName("lane11_Label")
        self.gridLayout.addWidget(self.lane11_Label, 5, 1, 1, 1)
        self.midi2_lane11_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane11_SpinBox.setMaximum(2000)
        self.midi2_lane11_SpinBox.setObjectName("midi2_lane11_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane11_SpinBox, 5, 5, 1, 1)
        self.auto_lane11_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane11_CheckBox.setChecked(True)
        self.auto_lane11_CheckBox.setObjectName("auto_lane11_CheckBox")
        self.gridLayout.addWidget(self.auto_lane11_CheckBox, 5, 2, 1, 1)
        self.key_lane_11_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_11_LineEdit.setObjectName("key_lane_11_LineEdit")
        self.gridLayout.addWidget(self.key_lane_11_LineEdit, 5, 6, 1, 1)
        self.lane18_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane18_Label.setAutoFillBackground(True)
        self.lane18_Label.setObjectName("lane18_Label")
        self.gridLayout.addWidget(self.lane18_Label, 6, 1, 1, 1)
        self.midi2_lane18_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane18_SpinBox.setMaximum(2000)
        self.midi2_lane18_SpinBox.setObjectName("midi2_lane18_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane18_SpinBox, 6, 5, 1, 1)
        self.auto_lane18_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane18_CheckBox.setChecked(True)
        self.auto_lane18_CheckBox.setObjectName("auto_lane18_CheckBox")
        self.gridLayout.addWidget(self.auto_lane18_CheckBox, 6, 2, 1, 1)
        self.key_lane_18_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_18_LineEdit.setObjectName("key_lane_18_LineEdit")
        self.gridLayout.addWidget(self.key_lane_18_LineEdit, 6, 6, 1, 1)
        self.midi1_lane18_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane18_SpinBox.setMaximum(2000)
        self.midi1_lane18_SpinBox.setObjectName("midi1_lane18_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane18_SpinBox, 6, 4, 1, 1)
        self.midi1_lane1C_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane1C_SpinBox.setMaximum(2000)
        self.midi1_lane1C_SpinBox.setObjectName("midi1_lane1C_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane1C_SpinBox, 7, 4, 1, 1)
        self.lane1C_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane1C_Label.setAutoFillBackground(True)
        self.lane1C_Label.setObjectName("lane1C_Label")
        self.gridLayout.addWidget(self.lane1C_Label, 7, 1, 1, 1)
        self.midi2_lane1C_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane1C_SpinBox.setMaximum(2000)
        self.midi2_lane1C_SpinBox.setObjectName("midi2_lane1C_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane1C_SpinBox, 7, 5, 1, 1)
        self.auto_lane1C_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane1C_CheckBox.setChecked(True)
        self.auto_lane1C_CheckBox.setObjectName("auto_lane1C_CheckBox")
        self.gridLayout.addWidget(self.auto_lane1C_CheckBox, 7, 2, 1, 1)
        self.key_lane_1C_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_1C_LineEdit.setObjectName("key_lane_1C_LineEdit")
        self.gridLayout.addWidget(self.key_lane_1C_LineEdit, 7, 6, 1, 1)
        self.midi1_lane1B_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane1B_SpinBox.setMaximum(2000)
        self.midi1_lane1B_SpinBox.setObjectName("midi1_lane1B_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane1B_SpinBox, 8, 4, 1, 1)
        self.lane1B_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane1B_Label.setAutoFillBackground(True)
        self.lane1B_Label.setObjectName("lane1B_Label")
        self.gridLayout.addWidget(self.lane1B_Label, 8, 1, 1, 1)
        self.midi2_lane1B_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane1B_SpinBox.setMaximum(2000)
        self.midi2_lane1B_SpinBox.setObjectName("midi2_lane1B_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane1B_SpinBox, 8, 5, 1, 1)
        self.auto_lane1B_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane1B_CheckBox.setChecked(True)
        self.auto_lane1B_CheckBox.setObjectName("auto_lane1B_CheckBox")
        self.gridLayout.addWidget(self.auto_lane1B_CheckBox, 8, 2, 1, 1)
        self.midi1_lane16_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane16_SpinBox.setMaximum(2000)
        self.midi1_lane16_SpinBox.setObjectName("midi1_lane16_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane16_SpinBox, 14, 4, 1, 1)
        self.key_lane_16_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_16_LineEdit.setObjectName("key_lane_16_LineEdit")
        self.gridLayout.addWidget(self.key_lane_16_LineEdit, 14, 6, 1, 1)
        self.midi1_lane12_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane12_SpinBox.setMaximum(2000)
        self.midi1_lane12_SpinBox.setObjectName("midi1_lane12_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane12_SpinBox, 9, 4, 1, 1)
        self.lane12_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane12_Label.setAutoFillBackground(True)
        self.lane12_Label.setObjectName("lane12_Label")
        self.gridLayout.addWidget(self.lane12_Label, 9, 1, 1, 1)
        self.midi2_lane12_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane12_SpinBox.setMaximum(2000)
        self.midi2_lane12_SpinBox.setObjectName("midi2_lane12_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane12_SpinBox, 9, 5, 1, 1)
        self.auto_lane12_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane12_CheckBox.setChecked(True)
        self.auto_lane12_CheckBox.setObjectName("auto_lane12_CheckBox")
        self.gridLayout.addWidget(self.auto_lane12_CheckBox, 9, 2, 1, 1)
        self.key_lane_12_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_12_LineEdit.setObjectName("key_lane_12_LineEdit")
        self.gridLayout.addWidget(self.key_lane_12_LineEdit, 9, 6, 1, 1)
        self.midi1_lane14_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane14_SpinBox.setMaximum(2000)
        self.midi1_lane14_SpinBox.setObjectName("midi1_lane14_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane14_SpinBox, 10, 4, 1, 1)
        self.lane14_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane14_Label.setAutoFillBackground(True)
        self.lane14_Label.setObjectName("lane14_Label")
        self.gridLayout.addWidget(self.lane14_Label, 10, 1, 1, 1)
        self.midi2_lane14_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane14_SpinBox.setMaximum(2000)
        self.midi2_lane14_SpinBox.setObjectName("midi2_lane14_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane14_SpinBox, 10, 5, 1, 1)
        self.auto_lane14_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane14_CheckBox.setChecked(True)
        self.auto_lane14_CheckBox.setObjectName("auto_lane14_CheckBox")
        self.gridLayout.addWidget(self.auto_lane14_CheckBox, 10, 2, 1, 1)
        self.key_lane_14_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_14_LineEdit.setObjectName("key_lane_14_LineEdit")
        self.gridLayout.addWidget(self.key_lane_14_LineEdit, 10, 6, 1, 1)
        self.midi1_lane13_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane13_SpinBox.setMaximum(2000)
        self.midi1_lane13_SpinBox.setObjectName("midi1_lane13_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane13_SpinBox, 11, 4, 1, 1)
        self.lane13_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane13_Label.setAutoFillBackground(True)
        self.lane13_Label.setObjectName("lane13_Label")
        self.gridLayout.addWidget(self.lane13_Label, 11, 1, 1, 1)
        self.midi2_lane13_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane13_SpinBox.setMaximum(2000)
        self.midi2_lane13_SpinBox.setObjectName("midi2_lane13_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane13_SpinBox, 11, 5, 1, 1)
        self.auto_lane13_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane13_CheckBox.setChecked(True)
        self.auto_lane13_CheckBox.setObjectName("auto_lane13_CheckBox")
        self.gridLayout.addWidget(self.auto_lane13_CheckBox, 11, 2, 1, 1)
        self.key_lane_13_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_13_LineEdit.setObjectName("key_lane_13_LineEdit")
        self.gridLayout.addWidget(self.key_lane_13_LineEdit, 11, 6, 1, 1)
        self.midi1_lane15_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane15_SpinBox.setMaximum(2000)
        self.midi1_lane15_SpinBox.setObjectName("midi1_lane15_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane15_SpinBox, 12, 4, 1, 1)
        self.lane15_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane15_Label.setAutoFillBackground(True)
        self.lane15_Label.setObjectName("lane15_Label")
        self.gridLayout.addWidget(self.lane15_Label, 12, 1, 1, 1)
        self.midi2_lane15_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane15_SpinBox.setMaximum(2000)
        self.midi2_lane15_SpinBox.setObjectName("midi2_lane15_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane15_SpinBox, 12, 5, 1, 1)
        self.auto_lane15_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane15_CheckBox.setChecked(True)
        self.auto_lane15_CheckBox.setObjectName("auto_lane15_CheckBox")
        self.gridLayout.addWidget(self.auto_lane15_CheckBox, 12, 2, 1, 1)
        self.key_lane_15_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_15_LineEdit.setObjectName("key_lane_15_LineEdit")
        self.gridLayout.addWidget(self.key_lane_15_LineEdit, 12, 6, 1, 1)
        self.midi1_lane17_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane17_SpinBox.setMaximum(2000)
        self.midi1_lane17_SpinBox.setObjectName("midi1_lane17_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane17_SpinBox, 13, 4, 1, 1)
        self.lane17_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane17_Label.setAutoFillBackground(True)
        self.lane17_Label.setObjectName("lane17_Label")
        self.gridLayout.addWidget(self.lane17_Label, 13, 1, 1, 1)
        self.midi2_lane17_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane17_SpinBox.setMaximum(2000)
        self.midi2_lane17_SpinBox.setObjectName("midi2_lane17_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane17_SpinBox, 13, 5, 1, 1)
        self.auto_lane17_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane17_CheckBox.setChecked(True)
        self.auto_lane17_CheckBox.setObjectName("auto_lane17_CheckBox")
        self.gridLayout.addWidget(self.auto_lane17_CheckBox, 13, 2, 1, 1)
        self.key_lane_17_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_17_LineEdit.setText("")
        self.key_lane_17_LineEdit.setObjectName("key_lane_17_LineEdit")
        self.gridLayout.addWidget(self.key_lane_17_LineEdit, 13, 6, 1, 1)
        self.lane16_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane16_Label.setAutoFillBackground(True)
        self.lane16_Label.setObjectName("lane16_Label")
        self.gridLayout.addWidget(self.lane16_Label, 14, 1, 1, 1)
        self.midi2_lane16_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane16_SpinBox.setMaximum(2000)
        self.midi2_lane16_SpinBox.setObjectName("midi2_lane16_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane16_SpinBox, 14, 5, 1, 1)
        self.auto_lane16_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane16_CheckBox.setChecked(True)
        self.auto_lane16_CheckBox.setObjectName("auto_lane16_CheckBox")
        self.gridLayout.addWidget(self.auto_lane16_CheckBox, 14, 2, 1, 1)
        self.lane19_Label = QtWidgets.QLabel(WidgetConfigurarDrum)
        self.lane19_Label.setAutoFillBackground(True)
        self.lane19_Label.setObjectName("lane19_Label")
        self.gridLayout.addWidget(self.lane19_Label, 15, 1, 1, 1)
        self.midi1_lane19_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi1_lane19_SpinBox.setMaximum(2000)
        self.midi1_lane19_SpinBox.setObjectName("midi1_lane19_SpinBox")
        self.gridLayout.addWidget(self.midi1_lane19_SpinBox, 15, 4, 1, 1)
        self.midi2_lane19_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDrum)
        self.midi2_lane19_SpinBox.setMaximum(2000)
        self.midi2_lane19_SpinBox.setObjectName("midi2_lane19_SpinBox")
        self.gridLayout.addWidget(self.midi2_lane19_SpinBox, 15, 5, 1, 1)
        self.auto_lane19_CheckBox = QtWidgets.QCheckBox(WidgetConfigurarDrum)
        self.auto_lane19_CheckBox.setChecked(True)
        self.auto_lane19_CheckBox.setObjectName("auto_lane19_CheckBox")
        self.gridLayout.addWidget(self.auto_lane19_CheckBox, 15, 2, 1, 1)
        self.key_lane_19_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.key_lane_19_LineEdit.setObjectName("key_lane_19_LineEdit")
        self.gridLayout.addWidget(self.key_lane_19_LineEdit, 15, 6, 1, 1)
        self.viewNotesButton = QtWidgets.QPushButton(WidgetConfigurarDrum)
        self.viewNotesButton.setObjectName("viewNotesButton")
        self.gridLayout.addWidget(self.viewNotesButton, 1, 4, 1, 1)
        self.viewNotesLineEdit = QtWidgets.QLineEdit(WidgetConfigurarDrum)
        self.viewNotesLineEdit.setObjectName("viewNotesLineEdit")
        self.gridLayout.addWidget(self.viewNotesLineEdit, 1, 5, 1, 1)

        self.retranslateUi(WidgetConfigurarDrum)
        QtCore.QMetaObject.connectSlotsByName(WidgetConfigurarDrum)
        WidgetConfigurarDrum.setTabOrder(self.saveConfigurationButton, self.exitButton)
        WidgetConfigurarDrum.setTabOrder(self.exitButton, self.portsConnectedButton)
        WidgetConfigurarDrum.setTabOrder(self.portsConnectedButton, self.portsConnectedTextEdit)
        WidgetConfigurarDrum.setTabOrder(self.portsConnectedTextEdit, self.portMidiSpinBox)
        WidgetConfigurarDrum.setTabOrder(self.portMidiSpinBox, self.auto_lane1A_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane1A_CheckBox, self.midi1_lane1A_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane1A_SpinBox, self.midi2_lane1A_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane1A_SpinBox, self.key_lane_1A_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_1A_LineEdit, self.auto_lane11_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane11_CheckBox, self.midi1_lane11_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane11_SpinBox, self.midi2_lane11_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane11_SpinBox, self.key_lane_11_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_11_LineEdit, self.auto_lane18_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane18_CheckBox, self.midi1_lane18_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane18_SpinBox, self.midi2_lane18_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane18_SpinBox, self.key_lane_18_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_18_LineEdit, self.auto_lane1C_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane1C_CheckBox, self.midi1_lane1C_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane1C_SpinBox, self.midi2_lane1C_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane1C_SpinBox, self.key_lane_1C_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_1C_LineEdit, self.auto_lane1B_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane1B_CheckBox, self.midi1_lane1B_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane1B_SpinBox, self.midi2_lane1B_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane1B_SpinBox, self.key_lane_1B_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_1B_LineEdit, self.auto_lane12_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane12_CheckBox, self.midi1_lane12_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane12_SpinBox, self.midi2_lane12_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane12_SpinBox, self.key_lane_12_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_12_LineEdit, self.auto_lane14_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane14_CheckBox, self.midi1_lane14_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane14_SpinBox, self.midi2_lane14_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane14_SpinBox, self.key_lane_14_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_14_LineEdit, self.auto_lane13_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane13_CheckBox, self.midi1_lane13_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane13_SpinBox, self.midi2_lane13_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane13_SpinBox, self.key_lane_13_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_13_LineEdit, self.auto_lane15_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane15_CheckBox, self.midi1_lane15_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane15_SpinBox, self.midi2_lane15_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane15_SpinBox, self.key_lane_15_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_15_LineEdit, self.auto_lane17_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane17_CheckBox, self.midi1_lane17_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane17_SpinBox, self.midi2_lane17_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane17_SpinBox, self.key_lane_17_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_17_LineEdit, self.auto_lane16_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane16_CheckBox, self.midi1_lane16_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane16_SpinBox, self.midi2_lane16_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane16_SpinBox, self.key_lane_16_LineEdit)
        WidgetConfigurarDrum.setTabOrder(self.key_lane_16_LineEdit, self.auto_lane19_CheckBox)
        WidgetConfigurarDrum.setTabOrder(self.auto_lane19_CheckBox, self.midi1_lane19_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi1_lane19_SpinBox, self.midi2_lane19_SpinBox)
        WidgetConfigurarDrum.setTabOrder(self.midi2_lane19_SpinBox, self.key_lane_19_LineEdit)

    def retranslateUi(self, WidgetConfigurarDrum):
        _translate = QtCore.QCoreApplication.translate
        WidgetConfigurarDrum.setWindowTitle(_translate("WidgetConfigurarDrum", "Form"))
        self.saveConfigurationButton.setText(_translate("WidgetConfigurarDrum", "Save configuration"))
        self.exitButton.setText(_translate("WidgetConfigurarDrum", "Exit configuration"))
        self.portsConnectedButton.setText(_translate("WidgetConfigurarDrum", "Ports connected"))
        self.midiPort_Label.setText(_translate("WidgetConfigurarDrum", "Selected Port MIDI"))
        self.midi1_Label.setText(_translate("WidgetConfigurarDrum", "Note MIDI"))
        self.midi2_Label.setText(_translate("WidgetConfigurarDrum", "or Note MIDI"))
        self.key_Label.setText(_translate("WidgetConfigurarDrum", "Key"))
        self.lane1A_Label.setText(_translate("WidgetConfigurarDrum", "Left Cymbal"))
        self.auto_lane1A_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane11_Label.setText(_translate("WidgetConfigurarDrum", "Hi Hat Close"))
        self.auto_lane11_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane18_Label.setText(_translate("WidgetConfigurarDrum", "Hi Hat Open"))
        self.auto_lane18_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane1C_Label.setText(_translate("WidgetConfigurarDrum", "Left Bass Drum"))
        self.auto_lane1C_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane1B_Label.setText(_translate("WidgetConfigurarDrum", "Hi Hat Foot"))
        self.auto_lane1B_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane12_Label.setText(_translate("WidgetConfigurarDrum", "Snare"))
        self.auto_lane12_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane14_Label.setText(_translate("WidgetConfigurarDrum", "High Tom"))
        self.auto_lane14_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane13_Label.setText(_translate("WidgetConfigurarDrum", "Right Bass Drum"))
        self.auto_lane13_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane15_Label.setText(_translate("WidgetConfigurarDrum", "Low Tom"))
        self.auto_lane15_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane17_Label.setText(_translate("WidgetConfigurarDrum", "Floor Tom"))
        self.auto_lane17_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane16_Label.setText(_translate("WidgetConfigurarDrum", "Cymbal"))
        self.auto_lane16_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.lane19_Label.setText(_translate("WidgetConfigurarDrum", "Ryde Cymbal"))
        self.auto_lane19_CheckBox.setText(_translate("WidgetConfigurarDrum", "Auto"))
        self.viewNotesButton.setText(_translate("WidgetConfigurarDrum", "View Notes on Port Selected"))

