# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WidgetConfigurarDTX.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetConfigurarDTX(object):
    def setupUi(self, WidgetConfigurarDTX):
        WidgetConfigurarDTX.setObjectName("WidgetConfigurarDTX")
        WidgetConfigurarDTX.resize(1280, 720)
        self.gridLayout = QtWidgets.QGridLayout(WidgetConfigurarDTX)
        self.gridLayout.setObjectName("gridLayout")
        self.perfect_time_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.perfect_time_Label.setObjectName("perfect_time_Label")
        self.gridLayout.addWidget(self.perfect_time_Label, 2, 6, 1, 1)
        self.speed_SpinBox = QtWidgets.QSpinBox(WidgetConfigurarDTX)
        self.speed_SpinBox.setMinimum(5)
        self.speed_SpinBox.setMaximum(5000)
        self.speed_SpinBox.setSingleStep(10)
        self.speed_SpinBox.setObjectName("speed_SpinBox")
        self.gridLayout.addWidget(self.speed_SpinBox, 3, 2, 1, 1)
        self.speed_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.speed_Label.setAutoFillBackground(True)
        self.speed_Label.setObjectName("speed_Label")
        self.gridLayout.addWidget(self.speed_Label, 3, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(WidgetConfigurarDTX)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 0, 1, 1, 2)
        self.good_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.good_Label.setAutoFillBackground(True)
        self.good_Label.setObjectName("good_Label")
        self.gridLayout.addWidget(self.good_Label, 4, 4, 1, 1)
        self.great_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.great_Label.setAutoFillBackground(True)
        self.great_Label.setObjectName("great_Label")
        self.gridLayout.addWidget(self.great_Label, 3, 4, 1, 1)
        self.theme_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.theme_Label.setAutoFillBackground(True)
        self.theme_Label.setObjectName("theme_Label")
        self.gridLayout.addWidget(self.theme_Label, 7, 1, 1, 1)
        self.good_time_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.good_time_Label.setObjectName("good_time_Label")
        self.gridLayout.addWidget(self.good_time_Label, 4, 6, 1, 1)
        self.perfect_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.perfect_Label.setAutoFillBackground(True)
        self.perfect_Label.setObjectName("perfect_Label")
        self.gridLayout.addWidget(self.perfect_Label, 2, 4, 1, 1)
        self.great_time_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.great_time_Label.setObjectName("great_time_Label")
        self.gridLayout.addWidget(self.great_time_Label, 3, 6, 1, 1)
        self.exitButton = QtWidgets.QPushButton(WidgetConfigurarDTX)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 0, 4, 1, 1)
        self.poor_time_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.poor_time_Label.setObjectName("poor_time_Label")
        self.gridLayout.addWidget(self.poor_time_Label, 5, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.theme_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDTX)
        self.theme_LineEdit.setObjectName("theme_LineEdit")
        self.gridLayout.addWidget(self.theme_LineEdit, 7, 2, 1, 1)
        self.checkBox_Gl = QtWidgets.QCheckBox(WidgetConfigurarDTX)
        self.checkBox_Gl.setChecked(True)
        self.checkBox_Gl.setObjectName("checkBox_Gl")
        self.gridLayout.addWidget(self.checkBox_Gl, 6, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 2, 1, 1)
        self.poor_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.poor_Label.setAutoFillBackground(True)
        self.poor_Label.setObjectName("poor_Label")
        self.gridLayout.addWidget(self.poor_Label, 5, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.songs_Label = QtWidgets.QLabel(WidgetConfigurarDTX)
        self.songs_Label.setObjectName("songs_Label")
        self.gridLayout.addWidget(self.songs_Label, 8, 1, 1, 1)
        self.songs_LineEdit = QtWidgets.QLineEdit(WidgetConfigurarDTX)
        self.songs_LineEdit.setObjectName("songs_LineEdit")
        self.gridLayout.addWidget(self.songs_LineEdit, 8, 2, 1, 1)

        self.retranslateUi(WidgetConfigurarDTX)
        QtCore.QMetaObject.connectSlotsByName(WidgetConfigurarDTX)
        WidgetConfigurarDTX.setTabOrder(self.saveButton, self.exitButton)
        WidgetConfigurarDTX.setTabOrder(self.exitButton, self.speed_SpinBox)
        WidgetConfigurarDTX.setTabOrder(self.speed_SpinBox, self.checkBox_Gl)
        WidgetConfigurarDTX.setTabOrder(self.checkBox_Gl, self.theme_LineEdit)

    def retranslateUi(self, WidgetConfigurarDTX):
        _translate = QtCore.QCoreApplication.translate
        WidgetConfigurarDTX.setWindowTitle(_translate("WidgetConfigurarDTX", "Form"))
        self.perfect_time_Label.setText(_translate("WidgetConfigurarDTX", "TextLabel"))
        self.speed_Label.setText(_translate("WidgetConfigurarDTX", "Speed"))
        self.saveButton.setText(_translate("WidgetConfigurarDTX", "Save Configuration"))
        self.good_Label.setText(_translate("WidgetConfigurarDTX", "Good"))
        self.great_Label.setText(_translate("WidgetConfigurarDTX", "Great"))
        self.theme_Label.setText(_translate("WidgetConfigurarDTX", "Theme"))
        self.good_time_Label.setText(_translate("WidgetConfigurarDTX", "TextLabel"))
        self.perfect_Label.setText(_translate("WidgetConfigurarDTX", "Perfect"))
        self.great_time_Label.setText(_translate("WidgetConfigurarDTX", "TextLabel"))
        self.exitButton.setText(_translate("WidgetConfigurarDTX", "Quit Configuration"))
        self.poor_time_Label.setText(_translate("WidgetConfigurarDTX", "TextLabel"))
        self.checkBox_Gl.setText(_translate("WidgetConfigurarDTX", "OpenGl"))
        self.poor_Label.setText(_translate("WidgetConfigurarDTX", "Poor"))
        self.songs_Label.setText(_translate("WidgetConfigurarDTX", "Songs"))

